LEGAL_CONCEPTS: set[str] = {
    # Contract fundamentals
    "binding_force",
    "contract_formation",
    "contract_modification",
    "contract_termination",
    "contract_validity",
    "offer_and_acceptance",
    "contractual_capacity",
    "consent",
    "object_of_contract",
    "cause_of_contract",
    "void_contract",
    "voidable_contract",
    "nullity",
    "rescission",
    "hardship",
    "force_majeure",
    "unforeseen_circumstances",

    # Obligations
    "obligation_source",
    "obligation_transfer",
    "obligation_extinction",
    "performance",
    "non_performance",
    "partial_performance",
    "delay_in_performance",
    "damages",
    "compensation",
    "penalty_clause",
    "liquidated_damages",
    "specific_performance",
    "joint_liability",
    "several_liability",
    "guaranty",
    "surety",
    "set_off",
    "novation",
    "assignment_of_rights",
    "debt_assignment",
    "subrogation",
    "waiver",
    "release",

    # Property and ownership
    "ownership",
    "possession",
    "real_property",
    "movable_property",
    "usufruct",
    "easement",
    "mortgage",
    "pledge",
    "lien",
    "property_transfer",
    "registration",
    "preemption_right",

    # Specific contract types
    "sale_contract",
    "lease_contract",
    "employment_contract",
    "service_contract",
    "agency_contract",
    "mandate",
    "loan_contract",
    "gift",
    "deposit_contract",
    "partnership_contract",
    "construction_contract",
    "insurance_contract",
    "arbitration_clause",
    "franchise_contract",

    # Commercial and corporate
    "commercial_paper",
    "bill_of_exchange",
    "promissory_note",
    "check",
    "endorsement",
    "letter_of_credit",
    "commercial_agency",
    "distribution_agreement",
    "company_formation",
    "shareholder_rights",
    "corporate_governance",

    # Dispute resolution and procedure
    "jurisdiction",
    "limitation_period",
    "statute_of_limitations",
    "prescription",
    "evidence_burden",
    "written_evidence",
    "expert_testimony",
    "judicial_notice",
    "enforcement",
    "execution",
    "provisional_measures",
    "injunction",
    "arbitration",
    "mediation",

    # Labor and employment
    "employment_termination",
    "wrongful_dismissal",
    "end_of_service",
    "working_hours",
    "annual_leave",
    "labor_dispute",
    "collective_bargaining",
    "non_compete",

    # Personal data and digital
    "data_protection",
    "data_subject_rights",
    "data_controller",
    "data_processor",
    "personal_data",
    "sensitive_data",
    "data_breach",
    "consent_data",
    "data_transfer",
    "electronic_signature",
    "electronic_contract",
    "digital_evidence",

    # Penalties and liability
    "criminal_liability",
    "civil_liability",
    "tort",
    "negligence",
    "strict_liability",
    "administrative_penalty",
    "fine",
    "imprisonment",
}

CONCEPT_LIST: list[str] = sorted(LEGAL_CONCEPTS)


def validate_concepts(concepts: list[str]) -> tuple[list[str], list[str]]:
    valid = [c for c in concepts if c in LEGAL_CONCEPTS]
    unknown = [c for c in concepts if c not in LEGAL_CONCEPTS]
    return valid, unknown
